#!/usr/bin/env bash
# Script displays "Best School" 10 times using a while loop.
# displays "Hi" before "Best School" On the 9th iteration.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
